name: JavaScript
on:
  pull_request:
    paths:
      - 'webpack/**'
      - 'package.json'
      - '.github/workflows/js_tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout Foreman
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install npm dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run Spellcheck (only warnings)
        run: npm run lint:spelling
      - name: Run tests
        run: npm run test
      - name: Publish Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
